package de.mhus.vance.shared.document.kind;

import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The computed overlay for a {@code kind: sheet} document — the
 * server-authoritative evaluated values, serialised under the top-level
 * {@code $computed} key by {@link SheetCodec}. Derived data: dropped on
 * the next {@link SheetCodec#parse}, regenerated by the brain-side
 * {@code SheetEvalService} (which stamps {@code computedAt}).
 *
 * <p>Mirrors the finance {@code $computed} pattern: {@code cell.data} is
 * the source (literal or formula), this overlay the computed result. Only
 * cells that actually compute (formulas) carry a {@link Value}; plain
 * literals are read straight from {@code data} by the client.
 *
 * <p>Spec: {@code specification/doc-kind-sheet.md} §6 (v2).
 */
public record SheetComputed(
        @Nullable String computedAt,
        List<Value> values) {

    public SheetComputed {
        if (values == null) values = List.of();
    }

    /**
     * One evaluated cell.
     *
     * @param field the A1 address.
     * @param value the computed value as a display-neutral string.
     * @param type  {@code number | text | boolean | date | error | empty}.
     * @param error the error token when {@code type == "error"} (else null).
     */
    public record Value(
            String field,
            String value,
            String type,
            @Nullable String error) {}
}
