package de.mhus.vance.brain.ws.handlers;

import de.mhus.vance.api.session.SessionMetadataDto;
import de.mhus.vance.api.session.SessionMetadataPatchRequest;
import de.mhus.vance.api.session.SessionStatus;
import de.mhus.vance.api.ws.MessageType;
import de.mhus.vance.api.ws.SessionMetadataPatchWsRequest;
import de.mhus.vance.api.ws.WebSocketEnvelope;
import de.mhus.vance.brain.permission.RequestAuthority;
import de.mhus.vance.brain.ws.ConnectionContext;
import de.mhus.vance.brain.ws.WebSocketSender;
import de.mhus.vance.brain.ws.WsHandler;
import de.mhus.vance.shared.permission.Action;
import de.mhus.vance.shared.permission.Resource;
import de.mhus.vance.shared.session.SessionDocument;
import de.mhus.vance.shared.session.SessionService;
import java.io.IOException;
import java.util.ArrayList;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;
import org.springframework.web.socket.WebSocketSession;
import tools.jackson.databind.ObjectMapper;

/**
 * WS counterpart of {@code PATCH /sessions/{id}/metadata}. Exposed so
 * the {@code foot} CLI (WS-only) can edit session title / icon / color
 * / tags / pin.
 *
 * <p>See {@code specification/session-lifecycle.md} §14.2.
 */
@Component
@RequiredArgsConstructor
public class SessionMetadataPatchHandler implements WsHandler {

    private final ObjectMapper objectMapper;
    private final WebSocketSender sender;
    private final SessionService sessionService;
    private final RequestAuthority authority;

    @Override
    public String type() {
        return MessageType.SESSION_METADATA_PATCH;
    }

    @Override
    public boolean canExecute(ConnectionContext ctx) {
        return ctx.hasSession();
    }

    @Override
    public void handle(ConnectionContext ctx, WebSocketSession wsSession, WebSocketEnvelope envelope)
            throws IOException {
        SessionMetadataPatchWsRequest req;
        try {
            req = objectMapper.convertValue(
                    envelope.getData(), SessionMetadataPatchWsRequest.class);
        } catch (IllegalArgumentException e) {
            sender.sendError(wsSession, envelope, 400,
                    "Invalid session-metadata-patch payload: " + e.getMessage());
            return;
        }
        if (req == null || req.getSessionId() == null || req.getSessionId().isBlank()) {
            sender.sendError(wsSession, envelope, 400, "sessionId is required");
            return;
        }

        SessionDocument session = sessionService.findBySessionId(req.getSessionId()).orElse(null);
        if (session == null || !session.getTenantId().equals(ctx.getTenantId())) {
            sender.sendError(wsSession, envelope, 404,
                    "Session '" + req.getSessionId() + "' not found");
            return;
        }
        if (!session.getUserId().equals(ctx.getUserId())) {
            sender.sendError(wsSession, envelope, 403,
                    "Session belongs to another user");
            return;
        }
        if (session.getStatus() == SessionStatus.CLOSED) {
            sender.sendError(wsSession, envelope, 409,
                    "Cannot patch metadata on a CLOSED session");
            return;
        }
        authority.enforce(ctx,
                new Resource.Session(ctx.getTenantId(), session.getProjectId(), session.getSessionId()),
                Action.WRITE);

        SessionMetadataPatchRequest restPatch = SessionMetadataPatchRequest.builder()
                .title(req.getTitle())
                .icon(req.getIcon())
                .color(req.getColor())
                .tags(req.getTags())
                .pinned(req.getPinned())
                .build();
        sessionService.patchMetadata(session.getSessionId(), restPatch);

        SessionDocument refreshed = sessionService.findBySessionId(session.getSessionId())
                .orElse(session);
        SessionMetadataDto reply = SessionMetadataDto.builder()
                .title(refreshed.getTitle())
                .titleAutoGenerated(refreshed.isTitleAutoGenerated())
                .icon(refreshed.getIcon())
                .color(refreshed.getColor())
                .tags(refreshed.getTags() == null
                        ? java.util.List.of()
                        : new ArrayList<>(refreshed.getTags()))
                .pinned(refreshed.isPinned())
                .build();
        sender.sendReply(wsSession, envelope, MessageType.SESSION_METADATA_PATCH, reply);
    }
}
