package de.mhus.vance.anus.compose;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Renders {@code docker-compose.yml} and the managed {@code .env} key set from a
 * {@link ComposeSetupState}.
 *
 * <p>The compose file is assembled from typed service fragments rather than a
 * templating engine: {@code mongodb}/{@code brain}/{@code face} are always
 * present, {@code redis} joins when live features are on, and the debug UIs
 * (mongo-express + redis-commander) plus the {@code anus} admin/setup service
 * ride along under Compose {@code profiles} so they never start with a plain
 * {@code docker compose up}. Concrete values are supplied by {@code .env} via
 * {@code ${VAR}} interpolation — the fragments only decide <b>which</b> services
 * exist, not their literal settings.
 */
final class ComposeFileRenderer {

    private ComposeFileRenderer() {}

    // ──────────────────────── .env ────────────────────────

    /** Builds the ordered map of {@code .env} keys the wizard manages. */
    static Map<String, String> renderEnv(ComposeSetupState s) {
        Map<String, String> env = new LinkedHashMap<>();
        env.put("VANCE_IMAGE_NAMESPACE", s.getImageNamespace());
        env.put("IMAGE_TAG", s.getImageTag());

        env.put("MONGO_INITDB_ROOT_USERNAME", s.getMongoUser());
        env.put("MONGO_INITDB_ROOT_PASSWORD", s.getMongoPassword());
        env.put("VANCE_MONGODB_DATABASE", s.getMongoDatabase());
        env.put("MONGO_PORT", Integer.toString(s.getMongoPort()));

        env.put("VANCE_ENCRYPTION_PASSWORD", s.getEncryptionPassword());
        env.put("VANCE_INTERNAL_TOKEN", s.getInternalToken());
        env.put("VANCE_BOOTSTRAP_ACME", "false");
        env.put("VANCE_FOOK_ENABLED", Boolean.toString(s.isFookEnabled()));
        env.put("BRAIN_PORT", Integer.toString(s.getBrainPort()));
        env.put("BRAIN_JAVA_OPTS", "-XX:+UseG1GC -XX:MaxRAMPercentage=75.0");

        env.put("VANCE_DEFAULT_LANGUAGE", s.getLanguageName());
        env.put("VANCE_DEFAULT_LANGUAGE_CODE", s.getLanguageCode());

        env.put("VANCE_REDIS_ENABLED", Boolean.toString(s.isRedisEnabled()));
        env.put("VANCE_REDIS_URI", "redis://redis:6379");
        env.put("REDIS_PORT", Integer.toString(s.getRedisPort()));

        env.put("FACE_PORT", Integer.toString(s.getFacePort()));

        env.put("VANCE_ANUS_PASSWORD_HASH", s.getAnusPasswordHash());

        if (s.isToolsEnabled()) {
            env.put("MONGO_EXPRESS_USERNAME", s.getMongoExpressUser());
            env.put("MONGO_EXPRESS_PASSWORD", s.getMongoExpressPassword());
            env.put("MONGO_EXPRESS_PORT", Integer.toString(s.getMongoExpressPort()));
            env.put("REDIS_UI_PORT", Integer.toString(s.getRedisUiPort()));
        }
        return env;
    }

    // ──────────────────────── docker-compose.yml ────────────────────────

    static String renderCompose(ComposeSetupState s) {
        StringBuilder sb = new StringBuilder();
        sb.append(HEADER);
        sb.append(MONGODB);
        if (s.isRedisEnabled()) {
            sb.append(REDIS);
        }
        sb.append(s.isRedisEnabled() ? BRAIN_WITH_REDIS : BRAIN_NO_REDIS);
        sb.append(FACE);
        if (s.isToolsEnabled()) {
            sb.append(MONGO_EXPRESS);
            if (s.isRedisEnabled()) {
                sb.append(REDIS_COMMANDER);
            }
        }
        sb.append(ANUS);
        sb.append(volumes(s));
        return sb.toString();
    }

    private static String volumes(ComposeSetupState s) {
        StringBuilder v = new StringBuilder("\nvolumes:\n");
        v.append("  mongo-data:\n");
        v.append("  brain-data:\n");
        v.append("  brain-logs:\n");
        v.append("  anus-data:\n");
        if (s.isRedisEnabled()) {
            v.append("  redis-data:\n");
        }
        return v.toString();
    }

    // ──────────────────────── fragments ────────────────────────

    private static final String HEADER = """
            # Generated by `vance-anus --setup-docker-compose`.
            #
            # Quick start:
            #   docker compose up -d
            #   docker compose run --rm anus --setup   # first-time tenant + user + LLM
            #   open http://localhost:8080
            #
            # Config lives in the sibling .env — edit it or re-run the wizard.

            name: vance

            services:
            """;

    private static final String MONGODB = """

              mongodb:
                image: mongo:7.0
                restart: unless-stopped
                environment:
                  MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
                  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
                  MONGO_INITDB_DATABASE: ${VANCE_MONGODB_DATABASE:-vance}
                volumes:
                  - mongo-data:/data/db
                ports:
                  - "${MONGO_PORT:-27017}:27017"
                healthcheck:
                  test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
                  interval: 10s
                  timeout: 5s
                  retries: 10
                  start_period: 20s
            """;

    private static final String REDIS = """

              redis:
                image: redis:7-alpine
                restart: unless-stopped
                ports:
                  - "${REDIS_PORT:-6379}:6379"
                volumes:
                  - redis-data:/data
                command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
                healthcheck:
                  test: ["CMD", "redis-cli", "ping"]
                  interval: 10s
                  timeout: 3s
                  retries: 5
                  start_period: 5s
            """;

    private static final String BRAIN_ENV_COMMON = """
                  SPRING_PROFILES_ACTIVE: prod
                  VANCE_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-example}@mongodb:27017/${VANCE_MONGODB_DATABASE:-vance}?authSource=admin
                  VANCE_MONGODB_DATABASE: ${VANCE_MONGODB_DATABASE:-vance}
                  VANCE_ENCRYPTION_PASSWORD: ${VANCE_ENCRYPTION_PASSWORD:-changeit}
                  VANCE_INTERNAL_TOKEN: ${VANCE_INTERNAL_TOKEN:-changeit-internal}
                  VANCE_BOOTSTRAP_ACME: ${VANCE_BOOTSTRAP_ACME:-false}
                  VANCE_FOOK_ENABLED: ${VANCE_FOOK_ENABLED:-true}
            """;

    private static final String BRAIN_TAIL = """
                  JAVA_OPTS: ${BRAIN_JAVA_OPTS:--XX:+UseG1GC -XX:MaxRAMPercentage=75.0}
                volumes:
                  - brain-data:/app/data
                  - brain-logs:/app/logs
                ports:
                  - "${BRAIN_PORT:-9990}:9990"
            """;

    private static final String BRAIN_NO_REDIS = """

              brain:
                image: ${VANCE_IMAGE_NAMESPACE:-mhus}/vance-brain:${IMAGE_TAG:-latest}
                restart: unless-stopped
                depends_on:
                  mongodb:
                    condition: service_healthy
                environment:
            """ + BRAIN_ENV_COMMON + BRAIN_TAIL;

    private static final String BRAIN_WITH_REDIS = """

              brain:
                image: ${VANCE_IMAGE_NAMESPACE:-mhus}/vance-brain:${IMAGE_TAG:-latest}
                restart: unless-stopped
                depends_on:
                  mongodb:
                    condition: service_healthy
                  redis:
                    condition: service_healthy
                environment:
            """ + BRAIN_ENV_COMMON + """
                  VANCE_REDIS_ENABLED: "true"
                  VANCE_REDIS_URI: ${VANCE_REDIS_URI:-redis://redis:6379}
            """ + BRAIN_TAIL;

    private static final String FACE = """

              face:
                image: ${VANCE_IMAGE_NAMESPACE:-mhus}/vance-face:${IMAGE_TAG:-latest}
                restart: unless-stopped
                depends_on:
                  brain:
                    condition: service_started
                ports:
                  - "${FACE_PORT:-8080}:80"
            """;

    private static final String MONGO_EXPRESS = """

              mongo-express:
                image: mongo-express:1.0
                restart: unless-stopped
                profiles: ["tools"]
                depends_on:
                  mongodb:
                    condition: service_healthy
                environment:
                  ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
                  ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
                  ME_CONFIG_MONGODB_SERVER: mongodb
                  ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME:-admin}
                  ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-admin}
                ports:
                  - "${MONGO_EXPRESS_PORT:-9081}:8081"
            """;

    private static final String REDIS_COMMANDER = """

              redis-commander:
                image: rediscommander/redis-commander:latest
                restart: unless-stopped
                profiles: ["tools"]
                depends_on:
                  redis:
                    condition: service_healthy
                environment:
                  REDIS_HOSTS: local:redis:6379
                ports:
                  - "${REDIS_UI_PORT:-8082}:8081"
            """;

    private static final String ANUS = """

              # Admin shell + first-time setup wizard. Not started by
              # `docker compose up`; invoke on demand:
              #   docker compose run --rm anus --setup   # tenant + user + LLM
              #   docker compose run --rm anus           # interactive admin REPL
              anus:
                image: ${VANCE_IMAGE_NAMESPACE:-mhus}/vance-anus:${IMAGE_TAG:-latest}
                profiles: ["tools"]
                depends_on:
                  mongodb:
                    condition: service_healthy
                stdin_open: true
                tty: true
                environment:
                  SPRING_PROFILES_ACTIVE: prod
                  VANCE_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-example}@mongodb:27017/${VANCE_MONGODB_DATABASE:-vance}?authSource=admin
                  VANCE_MONGODB_DATABASE: ${VANCE_MONGODB_DATABASE:-vance}
                  VANCE_ENCRYPTION_PASSWORD: ${VANCE_ENCRYPTION_PASSWORD:-changeit}
                  VANCE_ANUS_PASSWORD_HASH: ${VANCE_ANUS_PASSWORD_HASH:-}
                  VANCE_DEFAULT_LANGUAGE: ${VANCE_DEFAULT_LANGUAGE:-English}
                  VANCE_DEFAULT_LANGUAGE_CODE: ${VANCE_DEFAULT_LANGUAGE_CODE:-en}
                volumes:
                  - anus-data:/app/data
            """;
}
