package de.mhus.vance.anus.compose;

import lombok.Getter;
import lombok.Setter;
import org.jspecify.annotations.Nullable;

/**
 * Mutable state captured by {@link DockerComposeSetupWizard} — every knob that
 * ends up either as a {@code .env} variable or as a toggle in the generated
 * {@code docker-compose.yml}.
 *
 * <p>Defaults match the "safe for localhost" baseline of the hand-maintained
 * {@code vance-startup} stacks. On a re-run the wizard overwrites these from the
 * existing {@code .env} before showing the menu (see
 * {@link DockerComposeSetupWizard#prefillFromEnv}).
 *
 * <p>Secrets ({@link #mongoPassword}, {@link #encryptionPassword},
 * {@link #internalToken}) hold the literal value that lands in {@code .env};
 * {@link #anusPasswordHash} holds the already-BCrypt-hashed login password (the
 * plaintext is never stored on the state).
 */
@Getter
@Setter
class ComposeSetupState {

    // ── image source ──────────────────────────────────────────────
    private String imageNamespace = "mhus";
    /** Expert-only. */
    private String imageTag = "latest";

    // ── mongodb ───────────────────────────────────────────────────
    private String mongoUser = "root";
    /** Expert-only; generated by default. */
    private String mongoPassword = "";
    private String mongoDatabase = "vance";
    private int mongoPort = 27017;

    // ── brain secrets ─────────────────────────────────────────────
    /** Encrypts secret settings at rest. Set explicitly or generated. */
    private String encryptionPassword = "";
    /** Shared secret for cross-pod internal calls. Generated. */
    private String internalToken = "";

    // ── anus login ────────────────────────────────────────────────
    /** BCrypt hash of the admin-shell login password ({@code ""} = no gate). */
    private String anusPasswordHash = "";

    // ── feature toggles ───────────────────────────────────────────
    /** Fook bug/feature triage. Default off — opt-in, it reports out. */
    private boolean fookEnabled = false;
    /** Redis live-features. Expert-only to disable. */
    private boolean redisEnabled = true;
    /** Debug/admin UIs (mongo-express + redis-commander) under a compose profile. Expert-only. */
    private boolean toolsEnabled = false;
    /**
     * Persistent {@code anus} admin-shell service in the compose file. Expert-only,
     * default off — first-time setup runs as a one-shot {@code docker run} (see the
     * generated {@code setup.sh}), so the running stack never needs anus.
     */
    private boolean anusServiceEnabled = false;

    // ── access mode ───────────────────────────────────────────────
    /**
     * {@code false} = local (only the Vance/face port bound on {@code localhost});
     * {@code true} = reachable under an external URL / domain.
     */
    private boolean externalAccess = false;
    /** External browser-facing URL, e.g. {@code https://vance.example.de}. External mode only. */
    private String externalUrl = "";
    /**
     * External mode only: {@code true} = a bundled Caddy terminates TLS (auto-HTTPS
     * for the domain); {@code false} = plain HTTP on the Vance port, an upstream
     * (ngrok, Cloudflare Tunnel, external LB) does TLS.
     */
    private boolean caddyTls = true;

    // ── expert: host-port exposure (default: internal to the compose network) ──
    private boolean exposeBrainPort = false;
    private boolean exposeMongoPort = false;
    private boolean exposeRedisPort = false;

    // ── language (seeded later by the runtime --setup wizard) ──────
    /** Human-readable language name, e.g. {@code English}. */
    private String languageName = "English";
    /** ISO-ish short code, e.g. {@code en}. */
    private String languageCode = "en";

    // ── ports ─────────────────────────────────────────────────────
    private int brainPort = 9990;
    /** The single published front-door (Caddy) port — 9999 by default to sit
     * clear of a dev stack on 8080. */
    private int facePort = 9999;
    private int redisPort = 6379;
    private int mongoExpressPort = 9081;
    private int redisUiPort = 8082;

    // ── tools credentials (only written when toolsEnabled) ─────────
    private String mongoExpressUser = "admin";
    private String mongoExpressPassword = "admin";

    // ── wizard-local UI gate (never persisted) ────────────────────
    private boolean expertMode = false;

    /** Whether an existing {@code .env} was found and loaded on start. */
    private boolean loadedExisting = false;

    @Nullable String describeAnusLogin() {
        return anusPasswordHash.isBlank() ? null : "set";
    }
}
