package de.mhus.vance.anus.compose;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Minimal {@code .env} reader/writer for the docker-compose scaffolder.
 *
 * <p>{@link #read(Path)} parses {@code KEY=VALUE} lines into an ordered map
 * (comments and blank lines ignored, surrounding single/double quotes on the
 * value stripped). {@link #render(Map, Map)} produces the managed {@code .env}
 * body: the wizard's own keys in a fixed, commented layout, followed by any
 * pre-existing keys the wizard doesn't manage (so hand-added variables survive
 * a re-run).
 *
 * <p>Values are written verbatim, unquoted. Docker Compose does not
 * shell-interpolate {@code .env} values, and the compose file references every
 * secret via {@code ${VAR}} rather than inlining it, so a BCrypt hash's
 * {@code $} characters need no escaping here.
 */
final class DotEnvFile {

    private DotEnvFile() {}

    /** Parses an existing {@code .env}; returns an empty map if the file is absent. */
    static Map<String, String> read(Path file) throws IOException {
        Map<String, String> out = new LinkedHashMap<>();
        if (!Files.isRegularFile(file)) {
            return out;
        }
        for (String raw : Files.readAllLines(file, StandardCharsets.UTF_8)) {
            String line = raw.strip();
            if (line.isEmpty() || line.startsWith("#")) {
                continue;
            }
            int eq = line.indexOf('=');
            if (eq <= 0) {
                continue;
            }
            String key = line.substring(0, eq).strip();
            String value = line.substring(eq + 1).strip();
            out.put(key, unquote(value));
        }
        return out;
    }

    private static String unquote(String v) {
        if (v.length() >= 2
                && ((v.startsWith("\"") && v.endsWith("\""))
                        || (v.startsWith("'") && v.endsWith("'")))) {
            return v.substring(1, v.length() - 1);
        }
        return v;
    }

    /**
     * Renders the managed {@code .env} body.
     *
     * @param managed  ordered map of the wizard's own {@code KEY -> value}
     * @param existing everything parsed from the old file (used to carry over
     *                 unmanaged keys); may be empty
     */
    static String render(Map<String, String> managed, Map<String, String> existing) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by `vance-anus --setup-docker-compose`.\n");
        sb.append("#   ").append(de.mhus.vance.anus.BuildInfo.line()).append('\n');
        sb.append("# Edit by re-running the wizard, or by hand — a re-run preserves\n");
        sb.append("# any keys the wizard does not manage. Never commit your secrets.\n\n");

        section(sb, "Image source");
        put(sb, managed, "VANCE_IMAGE_NAMESPACE");
        put(sb, managed, "IMAGE_TAG");

        section(sb, "MongoDB");
        put(sb, managed, "MONGO_INITDB_ROOT_USERNAME");
        put(sb, managed, "MONGO_INITDB_ROOT_PASSWORD");
        put(sb, managed, "VANCE_MONGODB_DATABASE");
        put(sb, managed, "MONGO_PORT");

        section(sb, "Brain — CHANGE before exposing beyond localhost");
        put(sb, managed, "VANCE_ENCRYPTION_PASSWORD");
        put(sb, managed, "VANCE_INTERNAL_TOKEN");
        put(sb, managed, "VANCE_BOOTSTRAP_ACME");
        put(sb, managed, "VANCE_FOOK_ENABLED");
        put(sb, managed, "BRAIN_PORT");
        put(sb, managed, "BRAIN_JAVA_OPTS");

        section(sb, "Default language (seeded by the runtime `--setup` wizard)");
        put(sb, managed, "VANCE_DEFAULT_LANGUAGE");
        put(sb, managed, "VANCE_DEFAULT_LANGUAGE_CODE");

        section(sb, "Redis (live features)");
        put(sb, managed, "VANCE_REDIS_ENABLED");
        put(sb, managed, "REDIS_PORT");

        section(sb, "Front door (Caddy) + access");
        put(sb, managed, "VANCE_PORT");
        put(sb, managed, "VANCE_SITE_ADDRESS");
        put(sb, managed, "VANCE_ACCESS_MODE");
        put(sb, managed, "VANCE_WEB_PUBLICBASEURL");
        put(sb, managed, "VANCE_WEB_COOKIES_SECURE");
        put(sb, managed, "VANCE_EXTERNAL_URL");
        put(sb, managed, "VANCE_CADDY_TLS");

        section(sb, "Host-port exposure (expert; default: internal only)");
        put(sb, managed, "VANCE_EXPOSE_BRAIN");
        put(sb, managed, "VANCE_EXPOSE_MONGO");
        put(sb, managed, "VANCE_EXPOSE_REDIS");

        section(sb, "Anus admin shell");
        put(sb, managed, "VANCE_ANUS_SERVICE");
        put(sb, managed, "VANCE_ANUS_PASSWORD_HASH");

        if (managed.containsKey("MONGO_EXPRESS_USERNAME")) {
            section(sb, "Debug tools (profile: tools)");
            put(sb, managed, "MONGO_EXPRESS_USERNAME");
            put(sb, managed, "MONGO_EXPRESS_PASSWORD");
            put(sb, managed, "MONGO_EXPRESS_PORT");
            put(sb, managed, "REDIS_UI_PORT");
        }

        // Carry over anything the old file had that we don't manage.
        StringBuilder custom = new StringBuilder();
        for (Map.Entry<String, String> e : existing.entrySet()) {
            if (!managed.containsKey(e.getKey())) {
                custom.append(e.getKey()).append('=').append(e.getValue()).append('\n');
            }
        }
        if (custom.length() > 0) {
            section(sb, "Custom (carried over from your previous .env)");
            sb.append(custom);
        }
        return sb.toString();
    }

    private static void section(StringBuilder sb, String title) {
        sb.append("\n# --- ").append(title).append(' ');
        sb.append("-".repeat(Math.max(3, 60 - title.length())));
        sb.append('\n');
    }

    private static void put(StringBuilder sb, Map<String, String> managed, String key) {
        if (managed.containsKey(key)) {
            sb.append(key).append('=').append(managed.get(key)).append('\n');
        }
    }
}
