package de.mhus.vance.brain.access;

import de.mhus.vance.brain.execution.ExecutionRegistryEntry;
import de.mhus.vance.brain.execution.ExecutionRegistryService;
import de.mhus.vance.brain.execution.ExecutionScopeFilter;
import de.mhus.vance.brain.execution.ExecutionStatus;
import de.mhus.vance.brain.tools.exec.ExecLabels;
import de.mhus.vance.shared.jwt.VanceJwtClaims;
import jakarta.servlet.http.HttpServletRequest;
import java.util.List;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
 * Validates {@code SCRIPT_RUN} JWTs for the brain access filter.
 *
 * <p>Two independent checks:
 *
 * <ol>
 *   <li><b>Loopback origin</b> — the request must come from the local
 *       machine. The token issuer pairs it with a workspace subprocess
 *       running inside the same pod, so any cross-pod request carrying
 *       this token type is by definition stolen and rejected. Uses
 *       {@link HttpServletRequest#getRemoteAddr()} which returns the
 *       actual socket peer; HTTP-spoofable headers
 *       ({@code X-Forwarded-For}) are deliberately ignored.</li>
 *   <li><b>Execution still in flight</b> — the {@code srid} claim must
 *       correspond to an entry in {@link ExecutionRegistryService} whose
 *       status is {@link ExecutionStatus#RUNNING}. Token life-cycle is
 *       bound to job life-cycle; the TTL on the JWT is only a safety
 *       net.</li>
 * </ol>
 *
 * <p>Lookup is by the {@code cortex.runId} label set at spawn time
 * (see {@link ExecLabels}); the registry's job-id is opaque to the
 * issuer because it is generated by {@code ExecManager} during the
 * spawn — using a caller-allocated id as the JWT claim keeps the
 * issue-then-spawn order intact.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class ScriptRunAuthService {

    private final ExecutionRegistryService registry;

    public boolean isAcceptable(VanceJwtClaims claims, HttpServletRequest request) {
        if (claims.runId() == null || claims.runId().isBlank()) {
            log.debug("SCRIPT_RUN token rejected: missing srid claim");
            return false;
        }
        if (claims.projectId() == null || claims.projectId().isBlank()) {
            log.debug("SCRIPT_RUN token rejected: missing pid claim (runId='{}')",
                    claims.runId());
            return false;
        }
        if (!isLoopback(request)) {
            log.debug("SCRIPT_RUN token rejected: non-loopback peer '{}' for runId='{}'",
                    request.getRemoteAddr(), claims.runId());
            return false;
        }
        List<ExecutionRegistryEntry> hits = registry.list(
                ExecutionScopeFilter.all(),
                Map.of(ExecLabels.KEY_RUN_ID, claims.runId()));
        if (hits.isEmpty()) {
            log.debug("SCRIPT_RUN token rejected: unknown runId='{}'", claims.runId());
            return false;
        }
        boolean anyRunning = hits.stream()
                .anyMatch(e -> e.status() == ExecutionStatus.RUNNING
                        && claims.tenantId().equals(e.tenantId())
                        && claims.projectId().equals(e.projectId()));
        if (!anyRunning) {
            log.debug("SCRIPT_RUN token rejected: runId='{}' no longer RUNNING in scope "
                            + "(tenant='{}' project='{}')",
                    claims.runId(), claims.tenantId(), claims.projectId());
        }
        return anyRunning;
    }

    private static boolean isLoopback(HttpServletRequest request) {
        String remote = request.getRemoteAddr();
        if (remote == null) return false;
        return "127.0.0.1".equals(remote)
                || "0:0:0:0:0:0:0:1".equals(remote)
                || "::1".equals(remote)
                || "localhost".equals(remote);
    }
}
