package de.mhus.vance.api.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import de.mhus.vance.api.annotations.GenerateTypeScript;
import de.mhus.vance.api.common.AccentColor;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jspecify.annotations.Nullable;

/**
 * Partial-update request for {@link SessionMetadataDto}. Every field is
 * optional — {@code null} (or absent) means "do not change". Sending an
 * empty {@code tags} list is treated as "clear all tags"; omitting the
 * field leaves the tags unchanged.
 *
 * <p>The first invocation that actually changes a field stamps
 * {@code userTouchedAt} on the session document. Touching {@code title}
 * also flips {@code titleAutoGenerated} to {@code false}, locking the
 * LLM auto-suggester out for the remainder of the session's life.
 *
 * <p>See {@code specification/session-lifecycle.md} §14.2.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@GenerateTypeScript("session")
public class SessionMetadataPatchRequest {

    private @Nullable String title;

    private @Nullable String icon;

    private @Nullable AccentColor color;

    /**
     * If present, replaces the tag set. Empty list = clear tags. Omit
     * to leave the existing tags untouched.
     */
    private @Nullable List<String> tags;

    private @Nullable Boolean pinned;
}
