package de.mhus.vance.api.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import de.mhus.vance.api.annotations.GenerateTypeScript;
import de.mhus.vance.api.common.AccentColor;
import java.time.Instant;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jspecify.annotations.Nullable;

/**
 * Rich session list entry — includes user-facing metadata
 * (title/icon/color/tags/pinned), the denormalised chat preview, and
 * archive/runtime timestamps. Replaces the older
 * {@code de.mhus.vance.api.ws.SessionSummary} for REST list/search
 * paths; the WS summary stays around for the legacy WS list handler.
 *
 * <p>See {@code specification/session-lifecycle.md} §11, §14, §15.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@GenerateTypeScript("session")
public class SessionSummaryRichDto {

    private String sessionId;

    private String projectId;

    private SessionStatus status;

    /** Connection profile of the originator (foot / web / mobile / daemon). */
    private @Nullable String profile;

    private @Nullable Instant createdAt;

    private @Nullable Instant lastActivityAt;

    /** Set while {@code SUSPENDED}; cleared on resume/archive/close. */
    private @Nullable Instant suspendedAt;

    /** Set while {@code ARCHIVED}; cleared on reactivate. */
    private @Nullable Instant archivedAt;

    /** {@code true} while another connection currently holds the session lock. */
    private boolean bound;

    /**
     * {@code UserDocument.name} of the session owner. Exposed so the
     * Web-UI can tell apart "my own session" from "a shared session
     * owned by someone else" when both surface in the picker (see
     * {@code planning/multi-user-sessions.md} §2.5).
     */
    private String userId = "";

    // ─── User-facing metadata ───

    /** User-set or LLM-auto-suggested title. UI fallback: title → firstUserMessage → "Untitled". */
    private @Nullable String title;

    /** {@code true} while the title originates from the auto-suggester. */
    private boolean titleAutoGenerated;

    private @Nullable String icon;

    private @Nullable AccentColor color;

    private List<String> tags = List.of();

    private boolean pinned;

    /**
     * Multi-user permission for this session — see
     * {@code planning/multi-user-sessions.md} §2.1. Default
     * {@code false}; owner-only toggle via the session-metadata-patch
     * endpoint.
     */
    private boolean allowMultipleClients;

    /**
     * Recipe name the session-chat process was spawned from, or
     * {@code null} when the chat process was spawned without an
     * explicit recipe (engine-default). Surfaced for UI attribution —
     * pickers render it as a small badge next to status / last-activity
     * so users can spot which recipe a session runs on without opening
     * it. Sourced from the chat process's {@code recipeName} field at
     * list-time; the session itself does not persist the recipe.
     */
    private @Nullable String chatRecipe;

    // ─── Denormalised chat preview (set by ChatMessageService.append) ───

    /** Stable topic — first user message, truncated. */
    private @Nullable String firstUserMessage;

    /** "What happened last", truncated. Updated on every chat append. */
    private @Nullable String lastMessagePreview;

    /** Role of the message captured in {@link #lastMessagePreview}. */
    private @Nullable String lastMessageRole;

    private @Nullable Instant lastMessageAt;
}
