package de.mhus.vance.api.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import de.mhus.vance.api.annotations.GenerateTypeScript;
import java.time.Instant;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jspecify.annotations.Nullable;

/**
 * Rich session list entry — includes user-facing metadata
 * (title/icon/color/tags/pinned), the denormalised chat preview, and
 * archive/runtime timestamps. Replaces the older
 * {@code de.mhus.vance.api.ws.SessionSummary} for REST list/search
 * paths; the WS summary stays around for the legacy WS list handler.
 *
 * <p>See {@code specification/session-lifecycle.md} §11, §14, §15.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@GenerateTypeScript("session")
public class SessionSummaryRichDto {

    private String sessionId;

    private String projectId;

    private SessionStatus status;

    /** Connection profile of the originator (foot / web / mobile / daemon). */
    private @Nullable String profile;

    private @Nullable Instant createdAt;

    private @Nullable Instant lastActivityAt;

    /** Set while {@code SUSPENDED}; cleared on resume/archive/close. */
    private @Nullable Instant suspendedAt;

    /** Set while {@code ARCHIVED}; cleared on reactivate. */
    private @Nullable Instant archivedAt;

    /** {@code true} while another connection currently holds the session lock. */
    private boolean bound;

    // ─── User-facing metadata ───

    /** User-set or LLM-auto-suggested title. UI fallback: title → firstUserMessage → "Untitled". */
    private @Nullable String title;

    /** {@code true} while the title originates from the auto-suggester. */
    private boolean titleAutoGenerated;

    private @Nullable String icon;

    private @Nullable SessionColor color;

    private List<String> tags = List.of();

    private boolean pinned;

    // ─── Denormalised chat preview (set by ChatMessageService.append) ───

    /** Stable topic — first user message, truncated. */
    private @Nullable String firstUserMessage;

    /** "What happened last", truncated. Updated on every chat append. */
    private @Nullable String lastMessagePreview;

    /** Role of the message captured in {@link #lastMessagePreview}. */
    private @Nullable String lastMessageRole;

    private @Nullable Instant lastMessageAt;
}
