package de.mhus.vance.api.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import de.mhus.vance.api.annotations.GenerateTypeScript;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jspecify.annotations.Nullable;

/**
 * User-facing metadata on a session — title, icon, color, tags, pin
 * state. Read-side projection over the matching fields on the
 * persisted session document.
 *
 * <p>See {@code specification/session-lifecycle.md} §14.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@GenerateTypeScript("session")
public class SessionMetadataDto {

    /**
     * Session title. May be user-set or LLM-auto-suggested.
     * {@code null} until first auto-suggest or manual edit. UI fallback:
     * title → firstUserMessage → "Untitled".
     */
    private @Nullable String title;

    /**
     * {@code true} while {@link #title} was filled by the auto-suggester
     * and the user has not yet edited it manually. Flips to {@code false}
     * on the first user edit and stays there; subsequent auto-suggests
     * are inhibited.
     */
    private boolean titleAutoGenerated;

    /**
     * Unicode emoji (single codepoint or ZWJ sequence). {@code null}
     * means no icon set; UI falls back to a status-derived glyph.
     */
    private @Nullable String icon;

    /**
     * Accent color from the restricted palette. {@code null} means no
     * accent set.
     */
    private @Nullable SessionColor color;

    /**
     * User-supplied tags (lowercase, deduped, ≤20 entries, each ≤50 chars).
     * Empty when the user has not tagged the session.
     */
    private List<String> tags = List.of();

    /**
     * {@code true} if the user pinned this session — it floats to the
     * top of the default session list.
     */
    private boolean pinned;
}
