package de.mhus.vance.shared.llmusage;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jspecify.annotations.Nullable;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.CompoundIndexes;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * One pre-aggregated day per {@code (tenant, day, project, caller, recipe,
 * model, currency, kind)}. <b>This is the billing record.</b> The per-call
 * rows in {@link LlmUsageDocument} are diagnostics and expire; these do not
 * (by default).
 *
 * <h2>Why pre-aggregate instead of compacting nightly</h2>
 *
 * A nightly job needs a scheduler, a cross-pod lease, a watermark, catch-up
 * for the night no pod was running, and idempotency against a double run —
 * and permanently a report that unions two sources, because "today" is not
 * compacted yet. That last one never goes away. Incrementing on write costs
 * one atomic {@code $inc} and leaves today complete.
 *
 * <h2>Concurrency</h2>
 *
 * {@link #bucketId} <i>is</i> the key, hashed deterministically, so
 * concurrent writers from any number of pods land on the same document and
 * {@code $inc} merges them — there is no lost update. The one remaining race
 * is two writers inserting the same document at the same instant, which
 * MongoDB answers with a duplicate-key error on the upsert; the service
 * retries once and falls into the {@code $inc} branch.
 *
 * <h2>What is deliberately absent</h2>
 *
 * <ul>
 *   <li><b>No rate snapshot.</b> Cost is additive, rates are not: if a price
 *       changes mid-day there is no single correct rate for the row. The
 *       already-computed {@code cost*Micros} amounts are summed; the rate stays
 *       on the per-call row.</li>
 *   <li><b>No floating point.</b> Amounts are integer micro-units — see the
 *       comment on the fields. The per-call rows keep doubles because nothing
 *       accumulates them.</li>
 *   <li><b>No {@code outcome} in the key.</b> Failures are a second group of
 *       counters in the same document, which halves the row count and
 *       answers the usual question — what did it cost, how much went wrong —
 *       without a join.</li>
 *   <li><b>No attempt number.</b> In the aggregate only the count matters.</li>
 *   <li><b>No session or process.</b> That is drill-down, and drill-down is
 *       what the per-call rows are for.</li>
 * </ul>
 *
 * <p><b>{@link #day} is a UTC date.</b> Pre-aggregation gives up the freedom
 * to re-cut history into another timezone; that is acceptable only because
 * the young window (the per-call rows) stays re-cuttable. Anyone who needs
 * local billing days has to say so before the detail rows age out.
 */
@Document(collection = "llm_usage_daily")
@CompoundIndexes({
        @CompoundIndex(
                name = "usage_daily_tenant_day_idx",
                def = "{ 'tenantId': 1, 'day': 1 }"),
        @CompoundIndex(
                name = "usage_daily_tenant_project_day_idx",
                def = "{ 'tenantId': 1, 'projectId': 1, 'day': 1 }")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LlmUsageDailyDocument {

    /** Sentinel for a key field that has no value — hashed, and stored as-is. */
    public static final String NONE = "_none";

    private static final String ID_PREFIX = "usage_";
    private static final int ID_HEX_LENGTH = 32;

    /** The deterministic bucket key. Not generated by Mongo. */
    @Id
    private String bucketId = "";

    // ── Key dimensions ────────────────────────────────────────────
    private String tenantId = "";

    /** UTC day the calls fall into, as {@code yyyy-MM-dd}. */
    private String day = "";

    /** {@link #NONE} for tenant-scoped calls — a key field is never null. */
    private String projectId = NONE;

    /** Engine name, {@link LlmUsageService#CALLER_LIGHT}, or another subsystem. */
    private String caller = NONE;

    private String recipeName = NONE;

    /** Concrete model as the provider names it. */
    private String providerModel = NONE;

    /** Currency of every amount in this row. Never summed across rows. */
    private String currency = NONE;

    private UsageKind kind = UsageKind.CHAT;

    // ── Successful calls ──────────────────────────────────────────
    private long calls;
    private long tokensIn;
    private long tokensOut;
    private long cacheReadTokens;
    private long cacheWriteTokens;
    private long images;

    // Money is integer micro-units of `currency`, never a double.
    //
    // These fields are accumulated with $inc, once per attempt, forever — and
    // once the per-call rows have aged out they are the only record left, so
    // the sum has to be exact rather than merely close. Repeated IEEE-754
    // addition is neither: it loses low bits and it depends on the order the
    // attempts happened to arrive in, which for a billing record is the wrong
    // kind of surprise. One micro-unit is 1e-6 of the currency, which is finer
    // than any model's per-token price and comfortably inside a long for any
    // volume a tenant can produce in a day.
    //
    // Convert with LlmUsageService.toMicros / fromMicros; never format one of
    // these directly.
    private long costInputMicros;
    private long costOutputMicros;
    private long costCacheReadMicros;
    private long costCacheWriteMicros;
    private long costTotalMicros;

    // ── Failed attempts ───────────────────────────────────────────
    //
    // Own counters rather than own rows: a failed attempt is a fact about
    // the same bucket, and the report shows it next to the amount instead
    // of adding it in.
    private long callsFailed;
    private long tokensInFailed;
    private long tokensOutFailed;
    private long costFailedMicros;

    // ── Pricing coverage ──────────────────────────────────────────
    //
    // How much of this bucket had no price at all. Without it the report
    // shows a sum that looks complete while silently omitting every model
    // whose catalog entry lacks a `pricing:` block.
    private long unpricedCalls;
    private long unpricedTokensIn;
    private long unpricedTokensOut;

    /**
     * Successful calls whose provider reported no token counts at all.
     *
     * <p>A step beyond {@link #unpricedCalls}: there the tokens are known and
     * only the rate is missing, here neither is. Counted rather than dropped,
     * because a dropped row makes an endpoint disappear from the report
     * entirely — and an absent line reads as "nothing ran", which is the one
     * thing it does not mean.
     */
    private long unmeasuredCalls;

    private @Nullable Instant firstAt;
    private @Nullable Instant lastAt;

    /**
     * TTL anchor. {@code null} = keep forever, which is the default for the
     * billing record. Derived from {@link #day}, not from the write time, and
     * only set on insert — otherwise every {@code $inc} would push the expiry
     * out and a busy day would never age.
     */
    @Indexed(name = "usage_daily_ttl_idx", expireAfterSeconds = 0)
    private @Nullable Instant expiresAt;

    /**
     * Derive the bucket id. The {@code \0} separator matters: without it
     * {@code ("a","bc")} and {@code ("ab","c")} would hash the same, and
     * project names, caller names and recipe names are adjacent free text.
     */
    public static String bucketId(
            String tenantId,
            String day,
            String projectId,
            String caller,
            String recipeName,
            String providerModel,
            String currency,
            UsageKind kind) {
        String material = tenantId + '\0'
                + day + '\0'
                + projectId + '\0'
                + caller + '\0'
                + recipeName + '\0'
                + providerModel + '\0'
                + currency + '\0'
                + kind.name();
        return ID_PREFIX + sha256Hex(material).substring(0, ID_HEX_LENGTH);
    }

    /** UTC day string for {@code at}. */
    public static String dayOf(Instant at) {
        return LocalDate.ofInstant(at, ZoneOffset.UTC).toString();
    }

    /** Start of the UTC day {@code day} denotes — the anchor for expiry math. */
    public static Instant dayStart(String day) {
        return LocalDate.parse(day).atStartOfDay(ZoneOffset.UTC).toInstant();
    }

    /** {@link #NONE} for null/blank, so a key field never carries a null. */
    public static String key(@Nullable String raw) {
        return raw == null || raw.isBlank() ? NONE : raw;
    }

    private static String sha256Hex(String material) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(material.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder(hash.length * 2);
            for (byte b : hash) {
                sb.append(Character.forDigit((b >> 4) & 0xF, 16));
                sb.append(Character.forDigit(b & 0xF, 16));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 unavailable", e);
        }
    }
}
