package de.mhus.vance.addon.brain.wiki;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import org.springframework.stereotype.Component;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

/**
 * Build the {@code _backlinks.yaml} body from the resolved inbound-link
 * graph. Output is a YAML map {@code pageSlug -> [inbound slugs]} (planning
 * §3). Keys are sorted for a stable, diff-friendly artefact.
 *
 * <p>Slugs are unique per space but may repeat across spaces; when two
 * pages share a slug their inbound lists merge here (the same first-match
 * ambiguity the resolver accepts in v1).
 */
@Component
public class WikiBacklinksRenderer {

    /**
     * @param scan  the wiki scan (for relPath → slug lookup)
     * @param graph target {@code relativePath} → inbound {@code relativePath}s
     * @return YAML body for {@code _backlinks.yaml}
     */
    public String render(WikiFolderReader.Scan scan, Map<String, List<String>> graph) {
        Map<String, String> relToSlug = new LinkedHashMap<>();
        for (WikiPage p : scan.pages()) {
            relToSlug.put(p.relativePath(), p.slug());
        }

        Map<String, List<String>> out = new TreeMap<>();
        for (Map.Entry<String, List<String>> e : graph.entrySet()) {
            String targetSlug = relToSlug.getOrDefault(e.getKey(), e.getKey());
            List<String> inbound = out.computeIfAbsent(targetSlug, k -> new ArrayList<>());
            for (String rel : e.getValue()) {
                String s = relToSlug.getOrDefault(rel, rel);
                if (!inbound.contains(s)) inbound.add(s);
            }
            inbound.sort(String::compareTo);
        }

        DumperOptions opts = new DumperOptions();
        opts.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        opts.setPrettyFlow(false);
        String dumped = out.isEmpty() ? "{}\n" : new Yaml(opts).dump(out);
        return "# Auto-generated by the wiki app — rewritten on every app_rebuild.\n"
                + "# Map: page slug -> [slugs of pages that link here].\n"
                + dumped;
    }
}
