package de.mhus.vance.shared.inbox;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jspecify.annotations.Nullable;
import org.springframework.data.mongodb.core.mapping.Field;

/**
 * One contribution to a thread's clarification — embedded in
 * {@link MaximegalonDocument#getMessages()}.
 *
 * <p>A message has <b>no lifecycle of its own</b>: no status, no answer, no
 * effect. The thread carries the single decision it is heading towards, the
 * messages are the way there. A follow-up question that needs deciding is a
 * new thread, not a second ask in this one — otherwise the blocked process
 * could not tell which reply is its own.
 *
 * <p><b>{@link #id} is generated by us</b>, not by Mongo: an embedded document
 * gets no {@code _id} from the server, and the deep-link onto a single message
 * needs a stable address. Array indices would not survive a deletion.
 *
 * <p><b>{@link #parentId} instead of nesting.</b> The array stays flat even
 * though the document could hold the tree, because a flat array means
 * <em>one</em> update path — {@code messages.$[m]} with an array filter,
 * whatever depth the message logically sits at. Real nesting would need
 * {@code messages.$[m].readBy} for a root and
 * {@code messages.$[m].children.$[c].readBy} for a reply, so the write path
 * (every read, every reaction — the hottest one there is) would have to know
 * the level first. It also keeps the depth limit a matter of policy rather
 * than of structure: allowing depth 2 later is a UI change, not a migration.
 *
 * <p>See {@code planning/maximegalon.md} §3b.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MaximegalonMessage {

    /**
     * Stable id within the thread, assigned on append.
     *
     * <p><b>{@code @Field} is load-bearing.</b> Spring Data maps a field named
     * {@code id} onto {@code _id} by convention, even inside an embedded
     * document — so without this the stored key is {@code _id} while every
     * {@code arrayFilters} written against {@code messages.$[m].id} matches
     * nothing. That fails <em>silently</em>: the update is well-formed, Mongo
     * applies it to zero elements, and reads still return an id because the
     * mapper fills it back from {@code _id}. Reactions and per-message read
     * marks simply did nothing until this was pinned down.
     */
    @Field("id")
    private String id = "";

    private String authorUserId = "";

    /** Markdown body. */
    private String body = "";

    private @Nullable Instant createdAt;

    /**
     * The message this one replies to, or {@code null} for the root level —
     * which <em>is</em> the reply to the thread's own question, since the
     * thread is the root node of the tree (§3).
     */
    private @Nullable String parentId;

    /** Who has read this contribution. The truth behind the badge index. */
    @Builder.Default
    private List<String> readBy = new ArrayList<>();

    @Builder.Default
    private List<MaximegalonReaction> reactions = new ArrayList<>();
}
