import { computed, ref, type Ref } from 'vue';
import {
  AccentColor,
  SessionStatus,
  type SessionMetadataPatchRequest,
  type SessionSummaryRichDto,
} from '@vance/generated';
import {
  archiveSession,
  deleteSession,
  duplicateSession,
  getUsername,
  patchSessionMetadata,
  reactivateSession,
} from '@vance/shared';

/**
 * Callbacks that let a consumer react to a completed action. The
 * composable owns no session state itself — it operates on the passed-in
 * {@code session} ref and reports results back through these hooks. That
 * keeps it reusable both in {@code SessionHeader} (single session it
 * loads itself) and in the session-list menu (a session it borrows from
 * the list array).
 */
export interface SessionActionCallbacks {
  /** Fired after a successful metadata patch with the merged summary. */
  onPatched?: (updated: SessionSummaryRichDto) => void;
  onArchived?: () => void;
  onReactivated?: () => void;
  onDeleted?: () => void;
  /** Fired after a successful duplicate with the new session's business id. */
  onDuplicated?: (newSessionId: string) => void;
}

/**
 * Shared session lifecycle / metadata actions (pin, multi-user, color,
 * archive, reactivate, delete). Owner-gating and archived-state guards
 * live here so every surface behaves identically — see
 * planning/multi-user-sessions.md §2.4 (metadata actions are owner-only).
 *
 * The composable never mutates {@code session} in place; consumers wire
 * {@link SessionActionCallbacks} to apply the result to their own state.
 */
export function useSessionActions(
  session: Ref<SessionSummaryRichDto | null>,
  callbacks: SessionActionCallbacks = {},
) {
  const saving = ref(false);
  const error = ref<string | null>(null);

  /** True when the authenticated user owns the session. Shared sessions
   *  surface to non-owners as read-only participants. */
  const isOwner = computed(() => {
    const me = getUsername();
    return me !== null && session.value !== null && session.value.userId === me;
  });

  const isArchived = computed(
    () => session.value?.status === SessionStatus.ARCHIVED,
  );

  async function patch(p: SessionMetadataPatchRequest): Promise<void> {
    const s = session.value;
    if (!s) return;
    saving.value = true;
    error.value = null;
    try {
      const updated = await patchSessionMetadata(s.sessionId, p);
      const merged: SessionSummaryRichDto = {
        ...s,
        title: updated.title ?? undefined,
        titleAutoGenerated: updated.titleAutoGenerated,
        icon: updated.icon ?? undefined,
        color: updated.color ?? undefined,
        tags: updated.tags ?? [],
        pinned: updated.pinned,
        allowMultipleClients: updated.allowMultipleClients,
      };
      callbacks.onPatched?.(merged);
    } catch (e) {
      error.value = (e as Error).message;
    } finally {
      saving.value = false;
    }
  }

  async function togglePin(): Promise<void> {
    if (isArchived.value || !session.value) return;
    await patch({ pinned: !session.value.pinned });
  }

  async function toggleAllowMultipleClients(): Promise<void> {
    if (isArchived.value || !session.value) return;
    await patch({ allowMultipleClients: !session.value.allowMultipleClients });
  }

  async function setColor(value: AccentColor | null): Promise<void> {
    if (isArchived.value) return;
    // PATCH only sets values — null means "don't change". Clearing a
    // colour needs a controller sentinel; left for v2 (mirrors
    // SessionHeader's original behaviour).
    if (value === null) return;
    await patch({ color: value });
  }

  async function setIcon(value: string | null): Promise<void> {
    if (isArchived.value) return;
    await patch({ icon: value ?? '' });
  }

  async function setTags(value: string[]): Promise<void> {
    if (isArchived.value) return;
    await patch({ tags: value });
  }

  async function setTitle(title: string): Promise<void> {
    if (isArchived.value) return;
    await patch({ title });
  }

  async function archive(): Promise<void> {
    if (!session.value) return;
    saving.value = true;
    error.value = null;
    try {
      await archiveSession(session.value.sessionId);
      callbacks.onArchived?.();
    } catch (e) {
      error.value = (e as Error).message;
    } finally {
      saving.value = false;
    }
  }

  async function reactivate(): Promise<void> {
    if (!session.value) return;
    saving.value = true;
    error.value = null;
    try {
      await reactivateSession(session.value.sessionId);
      callbacks.onReactivated?.();
    } catch (e) {
      error.value = (e as Error).message;
    } finally {
      saving.value = false;
    }
  }

  async function remove(): Promise<void> {
    if (!session.value) return;
    saving.value = true;
    error.value = null;
    try {
      await deleteSession(session.value.sessionId);
      callbacks.onDeleted?.();
    } catch (e) {
      error.value = (e as Error).message;
    } finally {
      saving.value = false;
    }
  }

  /**
   * Duplicates the session (chat memory included) into a fresh copy. Works
   * regardless of archived state — the copy is created active. {@code title}
   * is the label for the copy (the caller localizes "Copy of …").
   */
  async function duplicate(title?: string): Promise<void> {
    if (!session.value) return;
    saving.value = true;
    error.value = null;
    try {
      const result = await duplicateSession(session.value.sessionId, title);
      callbacks.onDuplicated?.(result.sessionId);
    } catch (e) {
      error.value = (e as Error).message;
    } finally {
      saving.value = false;
    }
  }

  return {
    saving,
    error,
    isOwner,
    isArchived,
    patch,
    togglePin,
    toggleAllowMultipleClients,
    setColor,
    setIcon,
    setTags,
    setTitle,
    archive,
    reactivate,
    remove,
    duplicate,
  };
}
