package de.mhus.vance.shared.session;

import de.mhus.vance.api.ws.ClientType;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jspecify.annotations.Nullable;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.CompoundIndexes;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Persistent session record.
 *
 * <p>A session is created on first handshake and outlives the WebSocket
 * connection — the client may disconnect, another pod may pick it up
 * later. {@code boundConnectionId} marks which connection currently
 * holds the session; {@code null} means no one is connected (resumable).
 * {@code lastActivityAt} is touched on every inbound frame (atomically)
 * so a later cleanup job can time out idle sessions.
 *
 * <p>Pod-affinity has moved to the project level — see
 * {@link de.mhus.vance.shared.project.ProjectDocument#getPodIp()}. A
 * session implicitly inherits the affinity of its project, so the
 * session itself only tracks the connection that owns it, not the pod.
 *
 * <p>Exactly one connection may be bound at a time —
 * {@link SessionService#tryBind(String, String)} enforces this with a
 * conditional {@code updateFirst}.
 */
@Document(collection = "sessions")
@CompoundIndexes({
        @CompoundIndex(name = "sessionId_idx", def = "{ 'sessionId': 1 }", unique = true),
        @CompoundIndex(name = "tenant_user_idx", def = "{ 'tenantId': 1, 'userId': 1 }"),
        @CompoundIndex(name = "tenant_user_project_idx",
                def = "{ 'tenantId': 1, 'userId': 1, 'projectId': 1 }"),
        @CompoundIndex(name = "status_activity_idx", def = "{ 'status': 1, 'lastActivityAt': 1 }")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SessionDocument {

    @Id
    private @Nullable String id;

    /** Business id exposed to clients — {@code sess_...}. */
    private String sessionId = "";

    private String tenantId = "";

    /** Owning user — {@code UserDocument.name}. */
    private String userId = "";

    /** Project the session operates in — {@code ProjectDocument.name}. */
    private String projectId = "";

    private @Nullable String displayName;

    /** How the client is talking to us (CLI / desktop / mobile). */
    private ClientType clientType = ClientType.CLI;

    private String clientVersion = "";

    /** UUID generated by the pod that currently holds the connection, or {@code null} when idle. */
    private @Nullable String boundConnectionId;

    private SessionStatus status = SessionStatus.OPEN;

    /**
     * Mongo id of the auto-spawned session-chat think-process —
     * exists 1:1 with the session for its lifetime, engine taken
     * from the {@code session.defaultChatEngine} setting at
     * create-time. {@code null} only between session-create and
     * the first {@code SessionChatBootstrapper.ensureChatProcess}
     * call (or for sessions created before the bootstrapper
     * existed). Driven through {@link SessionService#setChatProcessId}
     * so a race can't link two chat-processes.
     */
    private @Nullable String chatProcessId;

    private Instant createdAt = Instant.EPOCH;

    /**
     * Last time anything happened on this session — updated atomically on every
     * inbound frame / heartbeat. Drives the idle-timeout cleanup job.
     */
    private Instant lastActivityAt = Instant.EPOCH;
}
